App/rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
      post :allow, :deny
    end
  end
  resources :microposts do
    member do
      post :allow, :deny, :like, :dislike, :retweet
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'

  get '/admin', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  post '/create_post/:tweet_id', to: 'microposts#post_tweet', as: 'create_post'

end

App/rails_app/app/views/shared/_delete_micropost.html.erb
<%= link_to "delete", feed_item, method:  :delete,
  confirm: "You sure?",
  title: feed_item.content %>

App/rails_app/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error"> 
      The Form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

App/rails_app/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

App/rails_app/app/views/shared/_feed_item.html.erb
<div class="col-xs-12 status">
  <div class="col-xs-12 status-top">
    <div class="col-xs-4 icon-user">
      <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    </div>
    <div class="col-xs-8 status-content">
      <div class="status-content-meta">
        <span class="user-name">
          <%= link_to feed_item.user.name, feed_item.user %>
        </span>
        <span class="elapsed-time">Posted <%= time_ago_in_words(feed_item.created_at) %> ago.</span>
      </div>
      <div class="status-content-text">
        <span>
          <%= wrap(feed_item.content) %>
        </span>
      </div>
    </div>
  </div>
  <div class="col-xs-12 status-bottom">
    <div class="col-xs-4 status-action">
      <label class="count-action"><%= feed_item.likes %></label>
      <%= link_to "", like_micropost_path(feed_item), method: :post, class: "glyphicon glyphicon-thumbs-up"  %>
      <!-- <span class="action-name">n</span> -->
    </div>
    <div class="col-xs-4 status-action">
      <label class="count-action"><%= feed_item.dislikes %></label>
      <%= link_to "", dislike_micropost_path(feed_item), method: :post, class: "glyphicon glyphicon-thumbs-down"  %>
      <!-- <span class="action-name">n</span> -->
    </div>
    <div class="col-xs-4 status-action">
      <label class="count-action"><%= feed_item.retweets %></label>
      <% if current_user == feed_item.user %>
        <span class="glyphicon glyphicon-retweet"></span>
      <% else %>
        <%= link_to "", retweet_micropost_path(feed_item), method: :post, 
          confirm: "Você tem certeza?", class: "glyphicon glyphicon-retweet" %>
      <% end %>
      <!-- <span class="action-name">n</span> -->
    </div>
  </div>
</div>

App/rails_app/app/views/shared/_home_not_signed.html.erb
<% if false %>
  <div class="center hero-unit">
    <h1>Welcome to the Sample App</h1>
    <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>
  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>
<div class="wrapper">
  <div class="col-xs-offset-1 col-xs-10 col-md-offset-4 col-md-4 txt-center">
    <div class="col-xs-4">
      <span class="glyphicon glyphicon-send main-icon"></span>
    </div>
    <div class="col-xs-8">
      <span class="">
        Compartilhe
      </span>
    </div>
  </div>
  <div class="col-xs-offset-1 col-xs-10 col-md-offset-4 col-md-4 btn-pdg">
    <div class="col-xs-6">
      <%= link_to "Cadastre-se", signup_path, class: "btn btn-default" %>
    </div>
    <div class="col-xs-6">
      <%= link_to "Entrar", signin_path, class: "btn btn-default" %>
    </div>
  </div>
</div>

App/rails_app/app/views/shared/_home_signed_in.html.erb
<% provide(:title, "Home") %>
<% provide(:glyph, "home") %>
<% provide(:header, "layouts/headers/home") %>

<div class="row">
<div class="span12">
  <h3>Micropost Feed</h3>
  <%= render 'shared/feed' %>
</div>
</div>

App/rails_app/app/views/shared/_micropost_admin.html.erb
<tr>
  <td><%= micropost_admin.content %></td>
  <td><%= micropost_admin.user.name %></td>
  <% if micropost_admin.active? %>
    <td>Ativo</td>
  <% else %>
    <td>Inativo</td>
  <% end %>
  <td>
    <% if micropost_admin.active? %>
      <%= link_to "deny", deny_micropost_path(micropost_admin), method: :post, confirm: "Você tem certeza?", class: "btn btn-default"  %>
    <% else %>
      <%= link_to "allow", allow_micropost_path(micropost_admin), method: :post, confirm: "Você tem certeza?", class: "btn btn-default" %>
    <% end %>
  </td>
</tr>

App/rails_app/app/views/shared/_micropost_form.html.erb
<%= form_for (@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field" >
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    <p id="counter">140 characters left</p>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

App/rails_app/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

App/rails_app/app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>