App/rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
      post :allow, :deny
    end
  end
  resources :microposts do
    member do
      post :allow, :deny, :like, :dislike, :retweet
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'

  get '/admin', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  post '/create_post/:tweet_id', to: 'microposts#post_tweet', as: 'create_post'

end

App/rails_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string
#  email           :string
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string
#  remember_token  :string
#  admin           :boolean
#

class User < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  has_secure_password
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship",
           dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  before_save { self.email.downcase! }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def feed
    Micropost.where(active: true)
  end

  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  def deny
    # Usei raw sql por causa da restrição de alteração do has_secure_password
    ActiveRecord::Base.connection.execute("UPDATE users SET active = false WHERE id = #{self.id}")
  end

  def allow
    # Usei raw sql por causa da restrição de alteração do has_secure_password
    ActiveRecord::Base.connection.execute("UPDATE users SET active = true WHERE id = #{self.id}")
  end

  def authenticate(unencrypted_password)
    if self.active?
      super(unencrypted_password)
    else
      false
    end
  end

  private
    
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

App/rails_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, 
    only: [:index, :edit, :update, :destroy, :following, :followers, :allow, :deny]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: [:destroy, :index, :allow, :deny]
  before_filter :block_signed_create, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Bem vindo ao Colé de Merma do RU!"
      redirect_to root_path
    else
      render 'new' end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.page(params[:page])
  end

  def index
    @users = User.page(params[:page])
    @microposts = Micropost.all.page(params[:page])
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Perfil atualizado."
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed"
    redirect_to users_path
  end

  def following 
    @title  = "Following"
    @user   = User.find(params[:id])
    @users  = @user.followed_users.page(params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user   = User.find(params[:id])
    @users  = @user.followers.page(params[:page])
    render 'show_follow'
  end

  def allow 
    User.find(params[:id]).allow
    flash[:success] = "Usuário ativado"
    redirect_to users_path
  end

  def deny 
    user = User.find(params[:id])
    unless user.admin?
      user.deny
      flash[:success] = "Usuário inativado."
    else
      flash[:error] = "Não é possível desativar um administrador."
    end
    redirect_to users_path
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  private

    def block_signed_create
      redirect_to root_path if signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path)  unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

App/rails_app/app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

App/rails_app/app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
  <div class="input-group">
    <div class="input-group-addon">
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    </div>
    <%= f.text_field :name, placeholder: 'Nome', class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="input-group">
    <div class="input-group-addon">
      <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
    </div>
    <%= f.text_field :email, placeholder: 'E-mail', class: "form-control" %>
  </div>
</div>

<% if false %>
<div class="form-group">
  <div class="input-group">
    <div class="input-group-addon">
      <span class="glyphicon glyphicon-education" aria-hidden="true"></span>
    </div>
    <%= f.text_field :course, placeholder: 'Curso', class: "form-control" %>
  </div>
</div>
<% end %>

<div class="form-group">
  <div class="input-group">
    <div class="input-group-addon">
      <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
    </div>
    <%= f.password_field :password, placeholder: "Senha", class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="input-group">
    <div class="input-group-addon">
      <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
    </div>
    <%= f.password_field :password_confirmation, placeholder:"Confirmação da senha", class: "form-control" %>
  </div>
</div>

App/rails_app/app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
            remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

App/rails_app/app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

App/rails_app/app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
              html: { method: :delete },
              remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

App/rails_app/app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <% if user.active? %>
    <td>Ativo</td>
  <% else %>
    <td>Inativo</td>
  <% end %>
  <td>
    <% unless user.admin? %>
      <% if user.active? %>
        <%= link_to "deny", deny_user_path(user), method: :post, confirm: "Você tem certeza?", class: "btn btn-default"  %>
      <% else %>
        <%= link_to "allow", allow_user_path(user), method: :post, confirm: "Você tem certeza?", class: "btn btn-default" %>
      <% end %>
    <% end %>
  </td>
</tr>

App/rails_app/app/views/users/edit.html.erb
<% provide(:title, "Meu Perfil") %>
<% provide(:glyph, "user") %>
<% provide(:header, "layouts/headers/profile") %>

<div class="col-xs-offset-1 col-xs-10 col-md-offset-4 col-md-4">
  <h2 class="main-content-title">Atualize seu perfil</h2>
  <%= form_for(@user) do |f| %>

    <%= render 'fields', f: f %>
    <%= f.submit "Salvar alterações", class: "btn btn-default" %>

  <% end %>

  <% if false %>
    <%= gravatar_for @user %>
    <%= link_to "change", "http://gravatar.com/emails", target: '_blank' %>
  <% end %>
</div>

App/rails_app/app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<% if false %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, confirm: "You sure?"  %>
  <% end %>
</li>
<% end %>

<ul class="nav nav-tabs" role="tablist" id="myTab">
  <li role="presentation" class="active">
    <a href="#users" aria-controls="users" role="tab" data-toggle="tab">Users</a>
  </li>
  <li role="presentation">
    <a href="#statuses" aria-controls="statuses" role="tab" data-toggle="tab">Statuses</a>
  </li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade in active" id="users">
    <table class="table table-striped table-bordered" id="lista_de_users">
      <thead id="status_list_header">
        <th>Nome</th>
        <th>Email</th>
        <th colspan="2">Status</th>
      </thead>
      <tbody id="status_list_body">
        <%= render @users %>
      </tbody>
    </table>
    <%= will_paginate @users %>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="statuses">
    <table class="table table-striped table-bordered" id="lista_de_statuses">
      <thead id="status_list_header">
        <th>Statuses</th>
        <th>Owner</th>
        <th colspan="2">Status</th>
      </thead>
      <tbody id="status_list_body">
        <%= render partial: 'shared/micropost_admin', collection: @microposts %>
      </tbody>
    </table>
    <%= will_paginate @microposts %>
  </div>
</div>

App/rails_app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

  <section class="container">
    <div class="col-xs-offset-1 col-xs-10 col-md-offset-4 col-md-4">
      <h2 class="main-content-title">Minhas Informações</h2>
      <%= form_for(@user) do |f| %>

        <%= render 'fields', f: f %>
        <div class="form-group button">
          <%= f.submit "Enviar", class: "btn btn-default" %>
        </div>

      <% end %>
    </div>
  </section>

App/rails_app/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <%= render 'follow_form' if signed_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

App/rails_app/app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1>
        <%= @user.name %>
      </h1>
      <span>
        <%= link_to "view my profile", @user %>
      </span>
      <span>
        <b>Microposts:</b> <%= @user.microposts.count %>
      </span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
        <% @users.each do |user| %>
          <%= link_to gravatar_for(user, size: 30), user %>
        <% end %>
      </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3>
      <%= @title %>
    </h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>