App/rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
      post :allow, :deny
    end
  end
  resources :microposts do
    member do
      post :allow, :deny, :like, :dislike, :retweet
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'

  get '/admin', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  post '/create_post/:tweet_id', to: 'microposts#post_tweet', as: 'create_post'

end

App/rails_app/app/views/layouts/_footer.html.erb
<% if signed_in? %>
  <footer class="text-center">
    <div class="col-xs-4">
      <%= link_to "", root_path, class: "glyphicon glyphicon-home" %>
    </div>
    <div class="col-xs-4">
      <a class="glyphicon glyphicon-send" href="<%= new_micropost_path %>"></a>
    </div>
    <div class="col-xs-4">
      <%= link_to "", edit_user_path(current_user), class: "glyphicon glyphicon-user" %>
    </div>
  </footer>
<% else %>
  <footer class="footer">
  </footer>
<% end %>

App/rails_app/app/views/layouts/_header.html.erb
<header class="header-text navbar navbar-fixed-top">
    <h1 class="header-text glyphicon glyphicon-<%= yield :glyph %>">
      <%= yield :title %>
    </h1>
      <%= link_to_if(signed_in?, "", signout_path, method: "delete", class: "header-logout glyphicon glyphicon-off") %>
<% if false %>
<!-- to newstatus use provide :glyph=send and the apropriate title -->
          <h1 class="header-text glyphicon glyphicon-user">
            <%= yield(:header) %>
              <% if signed_in? %>
                <% if false %>
                    <span class="glyphicon glyphicon-off"></span>
                <% end %>
                <%= link_to " o",  signout_path, method: "delete" %>
              <% end %>
          </h1>

  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",     root_path %></li>
          <li><%= link_to "Help",     help_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in",  signin_path %></li>
        <% end %>
        </ul>
      </nav>
    </div>
  </div>
<% end %>
</header>

App/rails_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

App/rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=320, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Colé de Merma do RU</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'  %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="wrapper">
        <section class="container">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
          <% end %>
          <%= yield %>
          <div class="col-xs-offset-1 col-xs-10 col-md-offset-4 col-md-4 btn-pdg">
            <%= debug(params) if Rails.env.development? %>
          </div>
        </section>
    </div>
    <% if false %>
      <div class="container">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    <% end %>
    <%= render 'layouts/footer' %>
  </body>
</html>